## 线上配置文件
## @author <a href="https://github.com/liyupi">程序员鱼皮</a>
## @from <a href="https://yupi.icu">编程导航知识星球</a>
##server:
##  port: 8101
#
#
#server:
#  port: 8101 # 确保这是你希望在生产环境中使用的端口
#  servlet:
#    context-path: /api    # 代理路径前缀
#    session:
#      cookie:
#        domain: 8.134.253.154 # 替换为你的生产域名
#  address: 0.0.0.0
#mybatis-plus:
#  configuration:
#    map-underscore-to-camel-case: false   # 取消下划线自动转换驼峰
#  global-config:
#    db-config:
#      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
#      logic-delete-value: 1 # 逻辑已删除值（默认为1）
#      logic-not-delete-value: 0 # 逻辑未删除值（默认为0）
#
#
#spring:
#  # 数据库配置
#  # todo 需替换配置
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/yuapi
#    username: yuapi
#    password: pFy6FJEyF6JpRcdA
#  # Redis 配置
#  # todo 需替换配置
#  redis:
#    database: 1
#    host: localhost
#    port: 6379
#
#
##    timeout: 5000
##    password: 123456
#
#
#  # Elasticsearch 配置
#  # todo 需替换配置
#
#
##  elasticsearch:
##    uris: http://localhost:9200
##    username: root
##    password: 123456
#
#
##mybatis-plus:
##  configuration:
##    # 生产环境关闭日志
##    log-impl: ''
#


# 公共配置文件
spring:
  application:
    name: yuapi
  # 生产环境
#  profiles:
#    active: prod
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session 配置
  session:
    # todo 取消注释开启分布式 session（须先配置 Redis）
    # store-type: redis
    # 30 天过期
    timeout: 2592000
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yuapi
    username: yuapi
    # todo 两个服务器修改了密码
    password: 07a5f621a4bee73e # TODO: 使用环境变量替代明文密码
  # Redis 配置
  redis:
    database: 1
    host: localhost
    port: 6379
#    timeout: 5000
#    password: 123456 # TODO: 使用环境变量替代明文密码
  # Elasticsearch 配置
#  elasticsearch:
#    uris: http://localhost:9200
#    username: root
#    password: 123456 # TODO: 使用环境变量替代明文密码
  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
server:
  address: 0.0.0.0
  port: 8101
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
# 微信相关
wx:
  # 微信公众平台
  mp:
    token: xxx # TODO: 使用环境变量替代明文token
    aesKey: xxx # TODO: 使用环境变量替代明文aesKey
    appId: xxx # TODO: 使用环境变量替代明文appId
    secret: xxx # TODO: 使用环境变量替代明文secret
    config-storage:
      http-client-type: HttpClient
      key-prefix: wx
      redis:
        host: 127.0.0.1
        port: 6379
      type: Memory
  # 微信开放平台
  open:
    appId: xxx # TODO: 使用环境变量替代明文appId
    appSecret: xxx # TODO: 使用环境变量替代明文appSecret
# 对象存储
cos:
  client:
    accessKey: xxx # TODO: 使用环境变量替代明文accessKey
    secretKey: xxx # TODO: 使用环境变量替代明文secretKey
    region: xxx # TODO: 使用环境变量替代明文region
    bucket: xxx # TODO: 使用环境变量替代明文bucket
dubbo:
  application:
    name: dubbo-springboot-demo-provider
  protocol:
    name: dubbo
    port: 20880
  registry:
    id: nacos-registry
    address: nacos://127.17.0.2:8848
#yuapi:
#  client:
#    secret-key: yupi
#    access-key: abcdefgh
